CONFIG_GPIO=y

# STEP 5.2 -Enable mcumgr DFU in application
# Enable MCUMGR 
CONFIG_MCUMGR=y
# Enable MCUMGR management for both OS and Images
CONFIG_MCUMGR_GRP_OS=y
CONFIG_MCUMGR_GRP_IMG=y
CONFIG_MCUMGR_GRP_OS_MCUMGR_PARAMS=y
CONFIG_MCUMGR_GRP_OS_INFO=y
CONFIG_MCUMGR_GRP_OS_DATETIME=y
# this is required for mcumgrctl -u . firmware update build/serial_recovery/zephyr/zephyr.signed.bin
CONFIG_MCUMGR_GRP_OS_BOOTLOADER_INFO=y

CONFIG_RTC=y



# Configure MCUMGR transport to UART
CONFIG_MCUMGR_TRANSPORT_UART=y
CONFIG_UART_MCUMGR=y

# Dependencies
# Configure dependencies for CONFIG_MCUMGR  
CONFIG_NET_BUF=y
CONFIG_ZCBOR=y
CONFIG_CRC=y

# Configure dependencies for CONFIG_MCUMGR_GRP_IMG  
CONFIG_FLASH=y
CONFIG_IMG_MANAGER=y

# Configure dependencies for CONFIG_IMG_MANAGER  
CONFIG_STREAM_FLASH=y
CONFIG_FLASH_MAP=y

# Configure dependencies for CONFIG_MCUMGR_TRANSPORT_UART 
CONFIG_BASE64=y
CONFIG_BOOTLOADER_MCUBOOT=y
CONFIG_LOG=y
CONFIG_UART_CONSOLE=y
CONFIG_MCUBOOT_GENERATE_CONFIRMED_IMAGE=y


CONFIG_SERIAL=y
CONFIG_UART_LINE_CTRL=y
CONFIG_CONSOLE=y

CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=y
