# STEP 1.1 - Enable MCUboot 
SB_CONFIG_BOOTLOADER_MCUBOOT=y

# STEP 1.2 - Configure bootloader to use only one slot. 
# STEP 5.1 - Go back to two slots, as we need two for DFU from the app
SB_CONFIG_MCUBOOT_MODE_SINGLE_APP=n
# f4系列不能用swap，只能single app模式或者overwrite模式
SB_CONFIG_MCUBOOT_MODE_SWAP_USING_MOVE=n
SB_CONFIG_MCUBOOT_MODE_OVERWRITE_ONLY=y